# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='昵称')),
                ('gender', models.CharField(choices=[(0, '男'), (1, '女'), (2, '保密')], default=0, max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('cover', models.CharField(max_length=50, verbose_name='头像')),
                ('introduce', models.CharField(max_length=140, verbose_name='简介')),
            ],
        ),
    ]
