# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pwd',
            field=models.CharField(default='', max_length=20, verbose_name='密码'),
        ),
    ]
