# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(default='1990-01-01', verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='users',
            name='pwd',
            field=models.CharField(default='123', max_length=20, verbose_name='密码'),
        ),
    ]
