# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180223_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(default='未知', max_length=2, verbose_name='性别'),
        ),
    ]
