# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('time', models.DateTimeField(verbose_name='发布时间')),
                ('hit', models.IntegerField(default=0, verbose_name='点击量')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect', models.IntegerField(default=0, verbose_name='收藏数')),
            ],
        ),
        migrations.CreateModel(
            name='LogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='LogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.CharField(max_length=140, verbose_name='评论')),
                ('time', models.DateTimeField(verbose_name='评论时间')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.Log')),
            ],
        ),
        migrations.CreateModel(
            name='LogReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=140)),
                ('time', models.DateTimeField(verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.LogComment')),
            ],
        ),
        migrations.CreateModel(
            name='LogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.Log')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log.LogCategory'),
        ),
    ]
